Repository mamba-org/gator, pull requests merged in 2025-06, with the labels that each got.

#235 Improve AsyncMock usage in tests to prevent StopAsyncIteration errors
  mamba_gator/tests/test_api.py
Labels: maintenance

#232 Upgrade Lerna to v7
  CONTRIBUTING.md
  lerna.json
  package.json
  yarn.lock
Labels: dependencies, maintenance

#239 Update to TypeScript 5.x
  package.json
  packages/common/jest.config.js
  packages/common/package.json
  packages/common/src/__tests__/services.spec.ts
  packages/common/src/components/CondaEnvToolBar.tsx
  packages/common/src/components/CondaPkgList.tsx
  packages/common/src/components/CondaPkgPanel.tsx
  packages/common/src/components/CondaPkgToolBar.tsx
  packages/common/src/components/NbConda.tsx
  packages/common/src/components/PkgGraph.tsx
  packages/common/src/services.ts
  packages/common/tsconfig.test.json
  packages/labextension/jest.config.js
  packages/labextension/package.json
  packages/navigator/package.json
  pyproject.toml
  tsconfig-base.json
  yarn.lock
Labels: dependencies, maintenance

#251 Upgrade KernelSpecManager to KernelSpec.IManager
  packages/labextension/package.json
  packages/labextension/src/__tests__/kernelspec.spec.ts
  packages/labextension/src/validator.ts
Labels: maintenance, javascript

#256 Update Jupyter Server to 2.x
  mamba_gator/tests/test_api.py
  mamba_gator/tests/utils.py
  pyproject.toml
Labels: dependencies, maintenance

#248 Fix crashes for R- and date-based versions
  mamba_gator/envmanager.py
  mamba_gator/tests/test_api.py
  mamba_gator/tests/test_manager.py
Labels: bug

#259 Add TODO for removing notebook config
  jupyter-config/jupyter_notebook_config.d/mamba_gator.json
Labels: maintenance

#271 Update changelog, replace yarn with jlpm
  .github/workflows/build.yml
  .github/workflows/publish.yml
  CONTRIBUTING.md
  README.md
  package.json
  packages/navigator/package.json
  pyproject.toml
Labels: documentation, maintenance
